# Generated by Django 4.1.10 on 2024-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedepartment',
            name='featured_image',
            field=models.ImageField(blank=True, default='profession/default.png', null=True, upload_to='profession/'),
        ),
    ]
