# Generated by Django 4.1.10 on 2024-04-07 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinical_laboratory_technician',
            old_name='hospital',
            new_name='service_provider',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='hospital',
            new_name='service_provider',
        ),
        migrations.RenameField(
            model_name='servicedepartment',
            old_name='hospital',
            new_name='service_provider',
        ),
        migrations.RenameField(
            model_name='specialization',
            old_name='hospital',
            new_name='service_provider',
        ),
        migrations.AddField(
            model_name='admin_information',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin_information',
            name='featured_image',
            field=models.ImageField(blank=True, default='admin/user-default.png', null=True, upload_to='admin/'),
        ),
        migrations.AlterField(
            model_name='admin_information',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
