# Generated by Django 4.1.10 on 2024-04-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_labworker',
            new_name='is_technicalSpecialist',
        ),
    ]
