# Generated by Django 4.1.10 on 2024-04-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nid',
        ),
    ]
