# Generated by Django 4.1.10 on 2024-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
