# Generated by Django 4.1.10 on 2024-04-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_provider_information',
            old_name='service_type',
            new_name='profession',
        ),
    ]
