# Generated by Django 4.1.10 on 2024-04-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_service_provider_admin',
        ),
    ]
