# Generated by Django 4.1.10 on 2024-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_rename_service_type_service_provider_information_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
