# Generated by Django 4.1.10 on 2024-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_client_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='featured_image',
            field=models.ImageField(blank=True, default='clients/user-default.png', null=True, upload_to='clients/'),
        ),
    ]
