# Generated by Django 4.1.10 on 2024-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_alter_client_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_provider_information',
            name='available_icu_no',
        ),
        migrations.RemoveField(
            model_name='service_provider_information',
            name='emergency_cabin_no',
        ),
        migrations.RemoveField(
            model_name='service_provider_information',
            name='general_bed_no',
        ),
        migrations.RemoveField(
            model_name='service_provider_information',
            name='regular_cabin_no',
        ),
        migrations.RemoveField(
            model_name='service_provider_information',
            name='vip_cabin_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='available_icu_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='emergency_cabin_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='general_bed_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='regular_cabin_no',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='vip_cabin_no',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('medical', 'Medical Services'), ('legal', 'Legal Services'), ('engineering', 'Engineering Services'), ('art', 'Art & Design'), ('tech', 'Technology Services'), ('education', 'Educational Services'), ('consulting', 'Consulting Services')], max_length=200),
        ),
    ]
