# Generated by Django 4.1.10 on 2024-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0008_remove_service_provider_information_available_icu_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='featured_image',
            field=models.ImageField(blank=True, default='services/default.png', null=True, upload_to='services/'),
        ),
    ]
