# Generated by Django 4.1.10 on 2024-04-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='report_fee',
        ),
    ]
