# Generated by Django 4.1.10 on 2024-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_information',
            name='availability',
            field=models.CharField(blank=True, default='9am - 4pm', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professional_information',
            name='services_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
