# Generated by Django 4.1.10 on 2024-04-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional_information',
            old_name='service_type',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='professional_information',
            old_name='service_type_name',
            new_name='profession_name',
        ),
    ]
