# Generated by Django 4.1.10 on 2024-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_information',
            name='consultation_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
