# Generated by Django 4.1.10 on 2024-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_rename_appointment_id_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_information',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
