# Generated by Django 4.1.10 on 2024-04-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_alter_professional_information_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional_information',
            name='report_fee',
        ),
    ]
