# Generated by Django 4.1.10 on 2024-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_rename_service_type_professional_information_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation_app', 'Consultation'), ('service_app', 'Service')], max_length=200),
        ),
    ]
