# Generated by Django 4.1.10 on 2024-04-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_remove_professional_information_report_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional_information',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='professional_information',
            name='nid',
        ),
    ]
