# Generated by Django 4.1.10 on 2024-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_professional_information_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_information',
            name='certificate_image',
            field=models.ImageField(blank=True, default='professionals_certificates/default.png', null=True, upload_to='professionals_certificates/'),
        ),
        migrations.AlterField(
            model_name='professional_information',
            name='featured_image',
            field=models.ImageField(default='professionals/user-default.png', upload_to='professionals/'),
        ),
    ]
