# Generated by Django 4.1.10 on 2024-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_information',
            name='services_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
