# Generated by Django 4.1.10 on 2024-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_alter_professional_information_certificate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional_information',
            old_name='department_name',
            new_name='service_type_name',
        ),
        migrations.RemoveField(
            model_name='professional_information',
            name='department',
        ),
        migrations.RemoveField(
            model_name='professional_information',
            name='service_provider',
        ),
        migrations.AlterField(
            model_name='professional_information',
            name='service_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical Services'), ('legal', 'Legal Services'), ('engineering', 'Engineering Services'), ('art', 'Art & Design')], max_length=200, null=True),
        ),
    ]
