# Generated by Django 4.0.6 on 2022-09-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0030_merge_20220915_1900'),
        ('professional', '0031_alter_prescription_test_test_description'),
    ]

    operations = [
    ]
