# Generated by Django 4.0.6 on 2022-09-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0036_merge_20220916_1041'),
        ('professional', '0037_merge_20220916_1045'),
    ]

    operations = [
    ]
