# Generated by Django 4.0.6 on 2022-09-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0040_merge_20220917_1537'),
        ('professional', '0042_merge_20220917_1959'),
    ]

    operations = [
    ]
