site_name: HealthStack
docs_dr: HEATH_DOC
nav:
  - Welcome: index.md
  - Homepage: service_provider.md
  - Admin:
      - Labworker: Lab_worker.md
      - Pharmacist: Pharmacist.md
      - ServiceProvider Admin: service_provider_admin.md
  - Professional Dashboard: professional.md
  - Client Dashboard: client.md
  - ABOUT: page2.md
