# Generated by Django 4.1.10 on 2024-04-10 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professional_service', '0001_initial'),
        ('professional_service_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clinical_Laboratory_Technician',
            new_name='Technical_Specialist',
        ),
    ]
